<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="userFeature.test"
    errors="1" failures="0" hostname="" id="" package="userFeature.test" skipped="0"
    tests="1" time="0.007000" timestamp="Fri, 16 Mar 2018 17:00:45 GMT">
  
    <testcase name="Users can see home page" classname="userFeature.test" time="0.007000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [User Feature Test / Users can see home page]:

  TypeError: client.url(...).waitForElementVisible(...).assert.visible(...).assert.visible(...).assert.containsText(...).assert.visible(...).assert.containsText(...).assert.visible(...).assert.containsText(...).assert.visible(...).assert.containsText(...).click(...).assertUrl is not a function
    at Object.Users can see home page (/Users/gbenga/Desktop/IdeaBox/e2e/test/userFeature.test.js:16:8)
    at Module.call (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/Users/gbenga/Desktop/IdeaBox/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
